from flask import Flask, jsonify, redirect, render_template, send_from_directory, url_for
import sqlite3

# Point Flask to the folders generated by react-scripts build
# https://stackoverflow.com/a/49860855/2108357
app = Flask(__name__, static_folder='build/static', template_folder='build')

@app.route('/')
def index():
	return render_template('index.html')

# Serve the Favicon, per the Flask docs
@app.route('/favicon.ico')
def favicon():
	return send_from_directory('build', 'favicon.ico', mimetype='image/vnd.microsoft.icon')

# Query our SQLite database for park reference data
@app.route('/api/parks')
def all_parks():
	connection = sqlite3.connect('parks.db')
	connection.row_factory = sqlite3.Row
	cursor = connection.cursor()
	rows = cursor.execute('SELECT * FROM Parks').fetchall()
	connection.close()
	parks = [dict(zip(row.keys(), row)) for row in rows]
	return jsonify(parks)
